#!/bin/bash
host=127.0.0.1
topic=meupc
usuario=usuario
senha=senha

# This script subscribes to a MQTT topic using mosquitto_sub.
# On each message received, you can execute whatever you want.

while true  # Keep an infinite loop to reconnect when connection lost/broker unavailable
do
    mosquitto_sub -h "192.168.1.2" -t "tecnocousaspc" -P $senha -u $usuario | while read -r payload
    do
        # Here is the callback to execute whenever you receive a message:
#        echo "Rx MQTT: ${payload}"
        ${payload}
    done
    sleep 10  # Wait 10 seconds until reconnection
    
    done # &  # Discomment the & to run in background (but you should rather run THIS script in background)
